# Tests generated by gpt
import pytest
import pandas as pd
from src.lib_linear_regression import RegressionOwn, RegressionGradient

from loguru import logger


logger.configure(handlers={})


@pytest.fixture
def sample_df():
    return pd.DataFrame({
        "Height(Inches)": [65, 70, 72],
        "Weight(Pounds)": [150, 180, 200],
    })

@pytest.fixture
def std_df():
    return pd.DataFrame({
        "Height": [165.1, 177.8, 182.88],  # cm
        "Weight": [68.04, 81.65, 90.72]    # kg
    })

def test_recalculate_to_si(sample_df):
    reg = RegressionOwn()
    reg.df = sample_df
    reg.recalculate_to_si()
    assert "Height" in reg.df.columns
    assert "Weight" in reg.df.columns
    assert reg.df["Height"].iloc[0] == pytest.approx(165.1, rel=1e-2)

def test_normalize_values(std_df):
    reg = RegressionOwn()
    reg.df = std_df
    reg.normalize_values()
    assert reg.df["Height_std"].max() == 1
    assert reg.df["Height_std"].min() == 0
    assert reg.df["Weight_std"].max() == 1
    assert reg.df["Weight_std"].min() == 0

def test_use_scikit_regression(std_df):
    reg = RegressionOwn()
    reg.df = std_df
    a, b = reg.use_scikit_regression("Height", "Weight")
    assert isinstance(a, float)
    assert isinstance(b, float)

def test_calculate_rss(std_df):
    reg = RegressionOwn()
    reg.df = std_df
    reg.normalize_values()
    rss = reg.calculate_rss(a=1, b=0)
    assert rss >= 0

def test_gradient_descent_works(std_df):
    reg = RegressionGradient()
    reg.df = std_df
    reg.normalize_values()
    a, b = reg.find_extremum_recurrence_gradient(0, 0, learning_rate=0.1, iterations_lim=100)
    assert isinstance(a, float)
    assert isinstance(b, float)

def test_own_recurrence_works(std_df):
    reg = RegressionOwn()
    reg.df = std_df
    reg.normalize_values()
    a, b = reg.find_extremum_recurrence_own(0, 0, step=0.1, iterations_lim=10)
    assert isinstance(a, float)
    assert isinstance(b, float)

def test_recalculate_linear_equation(std_df):
    reg = RegressionOwn()
    reg.df = std_df
    reg.normalize_values()
    a_std, b_std = 1.0, 0.0
    a, b = reg.recalculate_linear_equation(a_std, b_std)
    assert isinstance(a, float)
    assert isinstance(b, float)
